### ISSUE TITLE
Need Onyx Compatibility

### ISSUE THREAD

**Issue by CameronBodine** [CameronBodine/PINGMapper#30]
I though that I did incorporate Onyx compatibility, but not fully implemented yet.
```
(ping) E:\NAU\Python\PINGMapper>python main.py
['E:\\NAU\\Python\\PINGMapper\\testData\\Amberle_ONIX\\Rec00001\\B000.SON', 'E:\\NAU\\Python\\PINGMapper\\testData\\Amberle_ONIX\\Rec00001\\B001.SON', 'E:\\NAU\\Python\\PINGMapper\\testData\\Amberle_ONIX\\Rec00001\\B002.SON', 'E:\\NAU\\Python\\PINGMapper\\testData\\Amberle_ONIX\\Rec00001\\B003.SON', 'E:\\NAU\\Python\\PINGMapper\\testData\\Amberle_ONIX\\Rec00001\\B004.SON']

===========================================
===========================================
***** READING *****
working on .\procData\PINGMapperTest

Getting DAT Metadata...
Traceback (most recent call last):
  File "E:\NAU\Python\PINGMapper\main.py", line 69, in <module>
    read_master_func(sonFiles, humFile, projDir, t, nchunk, exportUnknown, wcp, wcr, detectDepth, smthDep, adjDep, pltBedPick, threadCnt)
  File "E:\NAU\Python\PINGMapper\src\main_readFiles.py", line 206, in read_master_func
    son._getEPSG()
  File "E:\NAU\Python\PINGMapper\src\class_sonObj.py", line 466, in _getEPSG
    lat = np.arctan(np.tan(np.arctan(np.exp(utm_n/ 6378388.0)) * 2.0 - 1.570796326794897) * 1.0067642927) * 57.295779513082302
UnboundLocalError: local variable 'utm_n' referenced before assignment
```

**Comment by CameronBodine** [comment]
Users will need to manually enter water type:
